name: pytests
on:
  push: { branches: [ main, master ] }
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    env: { MPLBACKEND: Agg }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11', cache: 'pip' }
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install pytest
      - name: Run tests
        run: |
          set +e
          pytest -q
          code=$?
          if [ "$code" -eq 5 ]; then echo "No tests collected. Skipping."; exit 0; fi
<<<<<<< HEAD
          exit "$code"
=======
          exit "$code"
>>>>>>> 4258880c074a8ad5a58bd2d13fe8ca9c24ec4d43
