name: pytests

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Dev deps are optional
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
<<<<<<< HEAD
          pip install pytest
      - name: Lint data
        run: |
            python tools/lint_data.py okun-law/data/raw/labor_panel_sample.csv
=======
          # Ensure pytest is available even if not listed
          python - <<'PY'
          import importlib, sys, subprocess
          if importlib.util.find_spec('pytest') is None:
              subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'pytest'])
          PY

>>>>>>> parent of 1dd2c06 (Update pytest.yml)
      - name: Run tests
        run: |
          set +e
          pytest -q
          code=$?
          if [ "$code" -eq 5 ]; then
            echo "No tests collected. Skipping.";
            exit 0
          fi
          exit "$code"
